### ISSUE TITLE
Organize magenta.music into library.

### ISSUE THREAD

**Issue by adarob** [magenta/magenta#1360]
We should start by re-organizing the functions in sequences_lib, etc. and exporting them directly under magenta.music.

**Comment by cifkao** [comment]
+1. There are functions and data structures in Magenta that could be very useful to the MIR community, but it can be impractical to have Magenta as a dependency. For example, I would like to use the `NoteSequence` proto to store some pre-processed MIDI files, but I can't install Magenta because I need to use an older version of TensorFlow.

If there's any way I can help with this, I can look into it.

**Comment by adarob** [comment]
Thanks for the offer! Like I mention here, a first step would be refactoring what's under magenta/music and exposing it (for now) as a library within magenta. That would make it easier to pull out later and put into its own package. Of course, totally separating it from tensorflow dependencies might be a challenge still...

**Comment by cghawthorne** [comment]
Most of the tensorflow dependencies are around tf.logging, which we can easily replace with abseil, and tf.gfile, which is more of a problem since we need it for internal compatibility. I suppose we could do something like write our own magenta.gfile wrapper, but that seems a little hacky.

**Comment by cifkao** [comment]
Maybe I misunderstood what "library" meant in this context (presumably it's about creating a Bazel rule and not a separate Python package). If that's the case, sorry for spamming this issue and I should probably create a new one.

**Comment by adarob** [comment]
No, it does mean a separate package. But before we can do that we first need to break all of the internal dependencies.

**Comment by cifkao** [comment]
OK, thanks for clarifying. So the goal would be to move the code (everything under `music` and `protobuf`?) to a new directory in this repo (eventually with its own `setup.py`), is that correct?

I tried to find things that `music` depends on. The only ones which I don't really see how to resolve are `pipeline.statistics` and `common.testing_lib`, which are imported in `music.*_lib` or the associated tests. On the other hand, many modules (notably `music.*_io` plus the protobuffers) seem to be already self-contained. I'm wondering if it would be reasonable to start by moving out the self-contained or easy-to-resolve things and leave the rest for later.

**Comment by cifkao** [comment]
I gave it a stab (see #1519). The only dependency left seems to be `pipeline.statistics`; I'm not sure what it does, but it doesn't seem to be music-specific enough to move it under `music`.

**Comment by adarob** [comment]
Thanks! @cghawthorne can you help review this?
Doing this will also allow us to put MAESTRO in TFDS.

**Comment by adarob** [comment]
I believe the next step is to make a pip package. @cghawthorne thoughts on how to best do this?

**Comment by cifkao** [comment]
Note that there is still the dependency on `pipelines.statistics` (imported e.g. from `chords_lib`).

**Comment by cghawthorne** [comment]
I think there might still be some tensorflow dependencies to trim too?

Once those are done, I think we can just add a new setup.py in the music subdir and modify our root setup.py to exclude the music subdir.

**Comment by cifkao** [comment]
I guess the TF dependencies can stay for now and potentially be removed later after the pip package is done?

As for the `pipelines.statistics` dependency, I can't think of any solution other than also making it a separate package (which does make some sense, since it already seems to be independent, and not tied to pipelines or anything else in Magenta in any way).

**Comment by cifkao** [comment]
@adarob @cghawthorne Any thoughts?

**Comment by adarob** [comment]
Sorry, but we are both currently out of the office. We'll get back to you
as soon as we can!

**Comment by cghawthorne** [comment]
@iansimon what do you think about the `pipelines.statistics` dependencies (e.g., in `drums_lib.py`)? I'm thinking we can maybe just move the extract_* methods that have that dependency to the relevant files in the pipelines directory.

**Comment by iansimon** [comment]
That's one option, another is to have those methods return a dict of plain old integer counts instead of a statistics.Counter.  I don't have a strong opinion.

**Comment by cifkao** [comment]
The methods could accept a dict of callback functions that would get called in place of `.increment()`. Then the caller would create their own `Counter`s and `Histogram`s (only for the statistics they actually need) and pass their `increment` methods as the callbacks.

**Comment by cifkao** [comment]
...something like this: #1551

**Comment by cghawthorne** [comment]
I dunno, I maybe lean toward just moving the extract_* methods out of music. We don't really want to encourage more use of the pipelines code because all our new pipeline-style code is using Beam, which has its own ideas about metrics.

**Comment by cghawthorne** [comment]
Thanks for the PR! As a followup, would you mind moving performance_rnn_pipeline and pianoroll_rnn_nade_pipeline into magenta.piplines? That way we won't have inter-model dependencies. Sorry, missed this in the initial review.

**Comment by cifkao** [comment]
OK, should be straightforward.

What doesn't seem as straightforward is making the pip package. After reading [this](https://packaging.python.org/guides/packaging-namespace-packages/) and [this](http://peak.telecommunity.com/DevCenter/setuptools#namespace-packages), I think there are two options moving forward:

- Make `magenta` a namespace package and keep `magenta.music` inside.
- Rename `magenta.music` to `magenta_music` (i.e. a completely separate package).

In both cases, `music` needs to be moved out into its own directory so that it can have its own `setup.py`, but the first option will allow it to stay logically inside `magenta`. However, it also **requires removing the top-level `__init__.py`** (I think this is to avoid shipping the same file in two different distributions) and I don't know if it's OK to do that.

**Comment by cghawthorne** [comment]
Hi @cifkao. @adarob and I were wondering if there's some way to preserve the current directory structure. From reading the [native namespace package docs](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages), it looks like the main reason `__init__.py` can't be in the main magenta directory is so that `find_packages` ignores it. However, you can pass an `exclude` list to `find_packages`. So, would it be possible to keep the existing directory structure, add `exclude=['magenta/music']` to the current setup.py, and then have a new setup.py in magenta/music for that package?

BTW, we'd be fine if the resulting packages only work with Python 3, since Python 2 support is going to end soon anyway.

**Comment by cifkao** [comment]
@cghawthorne 
> So, would it be possible to keep the existing directory structure, add `exclude=['magenta/music']` to the current setup.py, and then have a new setup.py in magenta/music for that package?

I doubt the `setup.py` can be *inside* the package it's supposed to install, usually it's one level above the top-level package (and it definitely needs to be run from there to find all the packages correctly).

> From reading the [native namespace package docs](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages), it looks like the main reason `__init__.py` can't be in the main magenta directory is so that `find_packages` ignores it.

I think (one of) the reason(s) is that normally when you `import pkg.subpkg`, `pkg`'s top-level `__init__.py` will run as well. In the namespace package case, you want to avoid this, because:

- You want `import pkg.subpkg` to behave consistently whether or not some other part of `pkg` is installed.
- You don't want to distribute two or more versions of the same `__init__.py` file.

The result is that a namespace package is really just a container for other packages rather than a full-fledged package. Anyway, I think that if you try to keep the current `__init__.py`, you might manage to make the setup work, but then the import mechanism will fail to recognize it as a namespace package and it won't work as expected.

Maybe all this just means that using a namespace package for this purpose is a bad idea, I don't know.

**Comment by cifkao** [comment]
I tried the trick with `find_packages(exclude=['magenta.music', 'magenta.music.*'])` and symlinking `magenta/music`. It seems to work with `setup.py`, but it breaks installing `magenta.music` with `pip install .` (because it doesn't follow the symlink). In any case, I still think it's not possible to keep magenta's `__init__.py` for this to work.

The other (IMO cleaner) option is to make the package completely separate (e.g. `magenta_music`), as I suggested above.

What do you think? @adarob @cghawthorne

**Comment by adarob** [comment]
@cifkao thanks again for your patience with us!

The challenging part is how we sync these changes up with our internal infrastructure, which isn't set up for these types of cases. 

We think the best approach is probably 2. Would you mind preparing a CL for that and we'll see if we can get it to be compatible with our internal codebase.

**Comment by cifkao** [comment]
@adarob Great!

There is already #1570, but it will probably need to be updated.

One more idea: According to [this](https://github.com/pypa/packaging.python.org/issues/295), it should be possible to have a namespace package inside a non-namespace package. So we could have a `magenta.lib` namespace package that `music` would get installed into, and keep the top-level `__init__.py`. Later some other independent or optional components of Magenta could also end up in `lib` (or whatever you would like to call it). So maybe that would be cleaner or easier to integrate in the internal codebase?

**Comment by cifkao** [comment]
@adarob I rebased #1570 to the current master, could you have a look now?

**Comment by cifkao** [comment]
Hi @adarob, I just wanted to check to see when you see this happening.

I will soon need to release my code which uses `NoteSequence`s, so I'm thinking of creating a provisional package containing only the code in `magenta.music` to depend on until this gets resolved. Let me know if I can do this in a way that would make it possible for you to reuse that.

**Comment by adarob** [comment]
Hi Ondrej,

Sorry about the delays on this. It is going to be a couple more weeks until
we can do this on our end, but I can commit to having it done by the end of
January.

-Adam

**Comment by cifkao** [comment]
Thank you Adam, that would be great!

**Comment by cifkao** [comment]
Any news on this? Any way I can help?

**Comment by adarob** [comment]
Thanks for the reminder Ondrej. I think we actually need to make these
changes internally first. I will get the ball rolling today.

**Comment by cifkao** [comment]
@adarob Sorry to bother you with this again, I'm just curious if there's anything new...

BTW, I might have some additions to sequences_lib once this is done!

**Comment by adarob** [comment]
Sorry that this still hasn't happened yet. @gauravmishra was leading this effort so I will follow up with him and update the thread on Wednesday.

**Comment by adarob** [comment]
So, we haven't been able to make progress on this internally thus far, but we are planning to move our repo to the magenta org in the next 2-3 weeks. I am setting a condition of that move that we split out the magenta music package. Stay tuned!

**Comment by adarob** [comment]
Fixed by eed016ad0f179e5896056d660653a6478a6a181c

**Comment by adarob** [comment]
New library exists at https://github.com/magenta/note-seq

**Comment by cifkao** [comment]
Great news!
