### ISSUE TITLE
The difference between the metrics of note_precision and onset_note_precision in train_util.py

### ISSUE THREAD

**Issue by guardian2020** [magenta/magenta#1796]
Hi!

I'm trying to replicate the model of "ONSETS AND FRAMES". In version 9885adef56 (corresponding to the paper), in train_util.py I'd like to know what's the difference between the metric (note_precision, note_recall, note_f1) and (onset_note_precision, onset_note_recall, onset_note_f1). Which group is corresponding to the standard Note-tracking metric (without considering offsets) in MIREX.

Anyone who knows about this?

**Comment by cghawthorne** [comment]
It's been a while since I looked at the code as it was in that commit, but I believe 'note_f1' uses the frame prediction output of the model and 'onset_note_f1' uses the onset prediction of the model. Both convert those predictions from a piano roll to a note sequence and then use mir_eval to compute the scores.

That said, what you really want is the output of `onsets_frames_transcription_infer`. The score that script outputs will include inference on the full length of the files and will combine the onset and frame predictions from the model into a single output. The `metrics/note_f1_score1` output of that script is most likely what you're looking for.
