### ISSUE TITLE
Can the tfrecords of Maestro offered be used for the program of the paper's version?

### ISSUE THREAD

**Issue by guardian2020** [magenta/magenta#1797]
Hi! 
I'm trying to replicate "onsets and frames" and working on the model of the version of the paper (9885adef56).
The paper's version uses MAPS dataset, while I saw the newer versions use Maestro.
I'd like to use 9885adef56, but with Maestro. However, it seems to take too long to build the tfrecords with onsets_frames_transcription_create_dataset.py, which seems to be only supporting one core of the cpu and not supporting gpus. Then I found the tfrecords of MAESTRO provided on the page of current version of onsets and frames: https://github.com/magenta/magenta/tree/master/magenta/models/onsets_frames_transcription
But I saw the file onsets_frames_transcription_create_dataset.py is different in the current version from the paper's version. So I wonder if I can directly use these tfrecords offered?

**Comment by cghawthorne** [comment]
I'm not sure if that will work or not, but you could certainly try! Is there a reason you want to use MAESTRO with the older code?

**Comment by guardian2020** [comment]
Thank you for your kind reply. The reason why I'm trying to use MAESTRO with the older code is just that I'd like to be sure the model is exactly the same version as the paper.
If it's not sure that the provided tfrecords created by the newer version of onsets_frames_transcription_create_dataset.py, do you think I can use the original version of onsets_frames_transcription_create_dataset.py to make the tfrecords myself? I ask this question is because I'm not sure whether there are any difference in the data structure or information included between MAPS and MAESTRO. Just a brief looking:
MAP contains an additional txt for each piece of music, which seemed never used by onsets_frames_transcription_create_dataset.py. So this doesn't seem to be a problem.
MAESTRO has the midi files with the extension of midi, while MAPS with mid
MAESTRO has additional files related to splitting datasets, which can be done manually also with the older version of the onsets_frames_transcription_create_dataset.py. So this doesn't seem to be a problem.
And if there's any other difference in the information contained in the midi files which could matter?

Thank you very much!

**Comment by cghawthorne** [comment]
The data used by Onsets and Frames from the two different datasets end up being basically the same: note start time, duration, and velocity. The goal of the dataset creation script is to take input from different datasets and convert it to a common input format.

The way that information is represented varies a little bit between MAPS and MAESTRO.  The txt files in MAPS have information that's equivalent to what's in the midi files (the extension doesn't matter). MAESTRO just uses midi files, but those midi files also contain some control changes that the MAPS ones don't (sostenuto and una corda), though this additional information is not used by Onsets and Frames. This is because the MAPS dataset started as MIDIs and was played back on a Disklavier, but MAESTRO started as live piano performances and was recorded by a Disklavier.

**Comment by guardian2020** [comment]
Thank you very much for your detailed reply! I'm sorry to reply to you so late, because I was very busy last month and didn't log in Github.

Your reply has helped me a lot to form a much clearer picture of these two datasets. I want to try to modify the code of onsets_frames_transcription_create_dataset.py of the paper's version for the MAESTRO dataset.
To achieve this, I'd like to further consult you one more question about this: 
You mentioned that midi files in MAESTRO contain some control information. I'd like to whether some of this control information would affect the actual onsets and offsets of the notes and (if yes) whether the onsets_frames_transcription_create_dataset.py of the paper's version has functions to process this information, (under the assumption that MAESTRO contains some _more_ control information than MAPS which affects the onsets and offsets of the notes). 
I ask this question because I saw you mentioned in the paper 
"
> _we first translate “sustain pedal” control changes into longer note durations. If a note is active when sustain goes on, that note will be extended until either sustain goes off or the same note is played again_

". 

Thank you very much!

**Comment by cghawthorne** [comment]
Yes, the dataset creation/parsing code that was used for the paper correctly processes the sustain control changes. Look for calls to `apply_sustain_control_changes`.

In V2 of the MAESTRO dataset, we include the following control changes: sostenuto (CC 66), una corda (CC 67), and sustain pedal (CC 64). We haven't explored processing any of those signals other than sustain, and our sustain handling is pretty simple: we consider sustain on if the value is >= 64, otherwise off.
