### ISSUE TITLE
Score2Perf: music_encoders.py question

### ISSUE THREAD

**Issue by heyzude** [magenta/magenta#1885]
Hi!
First of all, thank you for making this amazing set of codes for music :)

My question is, in score2perf problem, in the code min_pitch and max_pitch are set to 21, 108 respectively.
`music_encoders.MidiPerformanceEncoder(steps_per_second=100, num_velocity_bins=32, min_pitch=21, max_pitch=108, ...)`

Why are they set narrowly? The midi pitch ranges from 0 to 127. Is there some reasons for this?

And also, when decoding happens, I'm worried that maybe sometimes the transformer decodes to 0 or 1 (when add_eos),
in the middle of decoded performance events. This should not happen, but (though I don't throughly understand statistical aspect of deep learning models) I guess this may happen because model is kind of blackbox.
Do I have to worry about this?

Thanks!

**Comment by cghawthorne** [comment]
The range of notes on a standard piano is [21, 108]. The training datasets were all piano music, so that's why that range was used.

Yes, it's possible that the model could decode a 0 or 1. The 0 is unlikely because I think that isn't ever encountered in training. If I remember correctly, we would just ignore it on decode if it happened. Decoding an EOS token would just indicate that the model believes that is the end of the piece and we should stop decoding.
