### ISSUE TITLE
Train MusicVAE on the Expanded Groove Dataset

### ISSUE THREAD

**Issue by YawYoung** [magenta/magenta#1895]
Hi,

I tried to train MusicVAE model on the [Expanded Groove Dataset](https://magenta.tensorflow.org/datasets/e-gmd), but I found that [ROLAND_DRUM_PITCH_CLASSES](https://github.com/magenta/magenta/blob/master/magenta/models/music_vae/data.py#L55) is not compatible with Expanded Groove Dataset. (It is compatible for [Groove Dataset](https://magenta.tensorflow.org/datasets/groove))

Here are my questions:
1. How can I acquire the ROLAND_DRUM_PITCH_CLASSES which is compatible with Expanded Groove Dataset?
2. How is ROLAND_DRUM_PITCH_CLASSES constructed, when I have a new drum dataset, how to construct its PITCH_CLASSES?
3. Why the training pitch classes and inference pitch classes are different? https://github.com/magenta/magenta/blob/master/magenta/models/music_vae/configs.py#L522

**Comment by cghawthorne** [comment]
Hi @YawYoung. There's actually no need to train MusicVAE on E-GMD. E-GMD does have much more audio data than the original GMD (because we used a lot of different drum patches), but all the symbolic sequence data it has came from GMD. MusicVAE works in the symbolic domain, so training on GMD is best.
